POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "user3@user.com",
    "password": "123456"
}

###
GET http://localhost:3000/test-auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoidXNlcjNAdXNlci5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTcyMjUyMDg4OCwiZXhwIjoxNzIyNTIwOTQ4fQ.-anwZJgbWpOvZ8CNZWHycDbJueoxOm7Zi05YaOvnWn0